[tool.vendoring]
destination = "kritatwitch/vendor/"
requirements = "kritatwitch/vendor/vendors.txt"
namespace = "kritatwitch.vendor"

protected-files = ["__init__.py", "README.rst", "vendors.txt"]
patches-dir = "kritatwitch/tools/vendoring/patches"

[tool.vendoring.transformations]
substitute = [
  # {match = '__import__("twitch")', replace = '__import__("kritatwitch.vendor.twitch")'}
  { match='from \.extern', replace="from kritatwitch.vendor" }
]
drop = [
  "bin/",
  "*.so",
  "typing.*",
  "*/tests/"
]
